### ISSUE TITLE
Fatal location issue

### ISSUE THREAD

**Issue by dhruvnps** [Vivek-Aggala/weatherapp#1]
Cannot access homonyms

**Comment by sapieninja** [comment]
I too have been deeply affected by this issue plz fix

**Comment by Vivek-Aggala** [comment]
I understand your concerns

**Comment by dhruvnps** [comment]
> I too have been deeply affected by this issue plz fix

this issue is affecting millions. pls fix to prevent a meteorological crisis

**Comment by Vivek-Aggala** [comment]
Oh no
