### ISSUE TITLE
Developer response very slow

### ISSUE THREAD

**Issue by dhruvnps** [Vivek-Aggala/weatherapp#2]
Submitted an issue but nobody responded. Very disappointed. Considering an alternative application.

**Comment by sapieninja** [comment]
I too have been deeply affected by this issue.

**Comment by dhruvnps** [comment]
note, BBC whether dose not hav such isues

**Comment by Vivek-Aggala** [comment]
Poor spelling

**Comment by dhruvnps** [comment]
poor app

**Comment by dhruvnps** [comment]
pls reopen issue
